# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TqRNt-818VbfcDHaBlzRkl_gImQNhseV
"""

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC

class Model:
    def __init__(self):
        self.price_regressor = LinearRegression()
        self.server_predictor = SVC()

    def fit(self,x,y1, y2):
        self.price_regressor.fit(x, y1)
        self.server_predictor.fit(x, y2)

    def predict(self,x):
        price = self.price_regressor.predict(x)
        server = self.server_predictor.predict(x)

        return price, server

model = Model()

# new codes starts from here

import pandas as pd
import numpy as np

data=pd.read_csv('FinalData.csv')

x=data.drop(columns=['bandwidth_bytes','server_id','payload_size'])
# print(x)
y=data.drop(columns=['latency_seconds','availabity_seconds','price','payload_size','bandwidth_bytes'])

print(y.shape)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score


x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

columns_transformer= make_column_transformer((OneHotEncoder(sparse=False),['server_id']),remainder='passthrough')

# scaler=StandardScaler()
# lr=LinearRegression()

# pipe=make_pipeline(scaler,lr)

# pipe.fit(x_train,y_train)

# y_pred_lr=pipe.predict(x_test)

# print(r2_score(y_test,y_pred_lr))

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


rf = RandomForestClassifier()
rf.fit(x_train, y_train.values.ravel())


y_pred = rf.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

import pickle

pickle.dump(rf,open('Model2.pkl','wb'))